### ISSUE TITLE
Website checklist

### ISSUE THREAD

**Issue by AnaFranciscaS** [humanmade/out-of-office#6]
- [x] sponsor logos (some are currently linking to the wrong site) ref: #1  
- [ ] speakers block & speaker headshots 
- [x] Add bottom tier sponsors block 
- [x] add Friends & Ambassador logos to bottom tier sponsors block
- [x] Countdown timer ref: #3 
- [x] Fix section about Out of Office 2016 #5  

Ping me if you need to about any of this, thanks.

**Comment by AnaFranciscaS** [comment]
Also adding this here #5

**Comment by nomademoiselle** [comment]
- [x] Change Organising the event section with Logo of Human Made
- [x] Change facebook icon link to Out of Office FB page

**Comment by nomademoiselle** [comment]
Completed all task. Created a new issue for Speakers & Schedule since it's not on the same timeline. #8
